1st homework
RyzhkovNikita/ABBYY-Homework pull request #1
Opened 2019-11-06 05:21 UTC by RyzhkovNikita

2019-11-06 10:19 UTC, IvanShafran requested changes
Настрой, пожалуйста, .gitignore, чтобы .class не попадали в репозиторий.
Они генерируются при сборке автоматически, поэтому их нет смысла иметь под GIT

2019-11-06 10:59 UTC, RyzhkovNikita commented
Эти я сам сгенерил, но хорошо, не буду их пушить
--
Sent from Mail.ru app for Android Wednesday, 06 November 2019, 01:19pm +03:00 from Ivan Shafran  notifications@github.com :

>@IvanShafran requested changes on this pull request.
>Настрой, пожалуйста, .gitignore, чтобы .class не попадали в репозиторий.
>Они генерируются при сборке автоматически, поэтому их нет смысла иметь под GIT
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2019-11-16 15:02 UTC, IvanShafran commented
Я жду правок, если что)

2019-11-16 15:27 UTC, RyzhkovNikita commented
Ой, спасибо за напоминание, до завтрашнего вечера все будет)
--
Sent from Mail.ru app for Android Saturday, 16 November 2019, 06:02pm +03:00 from Ivan Shafran  notifications@github.com :

>Я жду правок, если что)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2019-11-17 19:25 UTC, IvanShafran approved these changes

2019-11-17 19:26 UTC, merged